#!/usr/bin/env python3
"""Schema-validation acceptance for the wyred emit contract (plan Step 1.3).

    python3 tests/run_schema_tests.py        # from the wyred-contract repo root

Drives tools/validate.py AS A SUBPROCESS — the way a consumer (and the future
Rust rewrite) would — to assert two things:

  1. PRISTINE: validating the untouched ga019 golden tree exits 0 and reports
     "114/114 valid" (invariant 1: goldens are never hand-edited to pass).
  2. MUTANTS: every committed fixture under tests/fixtures/ exits 1 AND names
     its expected JSON pointer + keyword in the FAIL line (proving the schema
     rejects what the emitter never produced, at the mutated location).

Fixtures are regenerated by tests/make_fixtures.py; the EXPECT map below is this
test's independent record of what each one must prove, so a drifted fixture (or
one added without wiring it in here) is a test failure. Mirrors wyred-audit's
tests/run_fixture_tests.py convention. Stdlib only; exit 0 iff every check holds.
"""
from __future__ import annotations

import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
VALIDATE = os.path.join(REPO, "tools", "validate.py")
GOLDENS = os.path.join(REPO, "goldens", "ga019")
FIXTURES = os.path.join(HERE, "fixtures")
SCHEMAS = os.path.join(REPO, "schemas")

# ga019 corpus size, counted as *.json the validator globs. Was 107; the ONE
# sanctioned golden-census event (WyredPlanIndex rule 4 / WyredSpiceContract §10)
# added intent_10_spice_divider's 7 JSON goldens (alloc/bom/cir.json/l1/l2/
# pinmap/records). Its non-JSON `.cir` deck is NOT globbed, so it does not count
# here. A drift OTHER than that recorded event is itself a finding.
GOLDEN_COUNT = 114
# eleven <kind>.schema.json + common.defs.json; the census event added
# cir.schema.json (the .cir.json confession sidecar, §5). Drift is a finding.
SCHEMA_COUNT = 12
DRAFT = "https://json-schema.org/draft/2020-12/schema"  # required $schema.
ID_PREFIX = "https://wyred.dev/contract/v0/"            # $id namespace (EMIT_CONTRACT Part E).

# fixture filename -> (JSON pointer, keyword) the FAIL line MUST carry.
# One mutant per spot-check category (plan 1.1a-c) + one per finding F10/F11/F12.
EXPECT = {
    # --- five-mutant spot check --------------------------------------------
    "mut_l1_drop_required.l1.json":            ("/", "required"),
    "mut_l2_bad_enum.l2.json":                 ("/components/0/terminals/0/role", "enum"),
    "mut_l2_extra_key.l2.json":                ("/", "additionalProperties"),
    "mut_bom_type.bom.json":                   ("/component_total", "type"),
    "mut_l2_three_element_node.l2.json":       ("/nets/0/nodes/0", "maxItems"),
    # --- const keyword (load-bearing: layer / path consts) -----------------
    "mut_l1_layer_const.l1.json":              ("/layer", "const"),
    # --- F10: bom `derived` biconditional, both directions -----------------
    "mut_bom_f10_authored_derived.bom.json":       ("/line_items/3", "oneOf"),
    "mut_bom_f10_generated_no_derived.bom.json":   ("/line_items/0", "oneOf"),
    # --- F11: pinmap l1_role XOR for_demand; alloc wiring net non-null ------
    "mut_pinmap_f11_both_provenance.pinmap.json":  ("/components/0", "oneOf"),
    "mut_alloc_f11_wiring_net_null.alloc.json":    ("/wiring/0/net", "type"),
    # --- F12: connlock / lifecycle closed gate-code vocabularies -----------
    "mut_connlock_f12_third_code.connlock.json":       ("/tamper_net_codes/1", "enum"),
    "mut_lifecycle_f12_sentinel.lifecycle.json":       ("/tamper_locked_edit_codes/1", "enum"),
}


def _run(*args):
    return subprocess.run([sys.executable, VALIDATE, *args],
                          capture_output=True, text=True)


def _check_stamps():
    """Assert the x-wyred-contract version stamp is present and consistent across
    every schema file (EMIT_CONTRACT Part E versioning convention). Returns a list
    of failure strings (empty == pass)."""
    import json
    fails = []
    paths = sorted(glob.glob(os.path.join(SCHEMAS, "*.json")))
    if len(paths) != SCHEMA_COUNT:
        fails.append("schema-set size %d != %d (%s)"
                     % (len(paths), SCHEMA_COUNT, [os.path.basename(p) for p in paths]))
    seen = set()
    for path in paths:
        base = os.path.basename(path)
        doc = json.load(open(path, encoding="utf-8"))
        if doc.get("$schema") != DRAFT:
            fails.append("%s: $schema %r != %r" % (base, doc.get("$schema"), DRAFT))
        if doc.get("$id") != ID_PREFIX + base:
            fails.append("%s: $id %r != %r" % (base, doc.get("$id"), ID_PREFIX + base))
        stamp = doc.get("x-wyred-contract")
        if not isinstance(stamp, dict):
            fails.append("%s: missing/!dict x-wyred-contract stamp" % base)
            continue
        if not isinstance(stamp.get("contract"), str) \
                or not isinstance(stamp.get("schema_rev"), int) \
                or isinstance(stamp.get("schema_rev"), bool):
            fails.append("%s: bad stamp shape %r (want {contract:str, schema_rev:int})"
                         % (base, stamp))
            continue
        seen.add((stamp["contract"], stamp["schema_rev"]))
    if len(seen) > 1:
        fails.append("inconsistent stamps across schemas: %s" % sorted(seen))
    return fails


def main():
    failures = 0

    # 0. STAMPS: every schema carries a present, consistent x-wyred-contract stamp.
    stamp_fails = _check_stamps()
    if stamp_fails:
        failures += len(stamp_fails)
        for msg in stamp_fails:
            print("FAIL stamp: %s" % msg)
    else:
        print("PASS stamps: %d schema(s) carry a consistent x-wyred-contract stamp"
              % SCHEMA_COUNT)

    # 1. PRISTINE tree -> exit 0, N/N valid.
    proc = _run("--tree", GOLDENS)
    want_line = f"{GOLDEN_COUNT}/{GOLDEN_COUNT} valid"
    if proc.returncode != 0 or want_line not in proc.stdout:
        failures += 1
        print("FAIL pristine: exit=%d (want 0), summary %r missing\n%s%s"
              % (proc.returncode, want_line, proc.stdout, proc.stderr))
    else:
        print("PASS pristine: %s, exit 0" % want_line)

    # 1b. every fixture named in EXPECT must exist, and every fixture on disk
    # must be wired into EXPECT (no orphan mutants that no check covers).
    on_disk = {os.path.basename(p) for p in glob.glob(os.path.join(FIXTURES, "*.json"))}
    for name in sorted(set(EXPECT) - on_disk):
        failures += 1
        print("FAIL fixture missing on disk: %s (run tests/make_fixtures.py)" % name)
    for name in sorted(on_disk - set(EXPECT)):
        failures += 1
        print("FAIL fixture not covered by EXPECT: %s (wire it into run_schema_tests.py)" % name)

    # 2. each MUTANT fixture -> exit 1, FAIL line names its pointer + keyword.
    for name, (pointer, keyword) in sorted(EXPECT.items()):
        path = os.path.join(FIXTURES, name)
        if not os.path.exists(path):
            continue  # already counted above
        proc = _run("--file", path)
        fail_lines = [ln for ln in proc.stdout.splitlines() if ln.startswith("FAIL ")]
        hit = any((("  %s  " % pointer) in ln) and (("[%s]" % keyword) in ln)
                  for ln in fail_lines)
        if proc.returncode != 1 or not hit:
            failures += 1
            print("FAIL mutant %-42s exit=%d (want 1); expected pointer %r [%s] "
                  "not found\n    %s"
                  % (name, proc.returncode, pointer, keyword,
                     "\n    ".join(fail_lines) or "(no FAIL lines)"))
        else:
            print("PASS mutant %-42s exit 1; %s [%s]" % (name, pointer, keyword))

    print("\nSCHEMA TESTS: %s (%d failure(s))"
          % ("PASS" if failures == 0 else "FAIL", failures))
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
